# Generated by Django 3.1.5 on 2021-02-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_dir', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email_add',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
