# Generated by Django 3.1.5 on 2021-02-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_dir', '0003_auto_20210220_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email_add',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
